# Generated by Django 3.2.8 on 2022-03-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("firebase_uid", models.CharField(max_length=512)),
                ("phone_number", models.CharField(max_length=50)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("profil_image", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("firebase_uid",),
                name="unique_firebase_uid_if_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted__isnull", True), ("username__isnull", False)
                ),
                fields=("username",),
                name="unique_username_if_not_deleted",
            ),
        ),
    ]
