# Generated by Django 3.2.8 on 2022-03-25 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "bill",
            },
        ),
        migrations.CreateModel(
            name="SplitBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("withdrawal_method", models.CharField(max_length=128)),
                ("wirhdrawal_number", models.CharField(max_length=128)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "split_bill",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["firebase_uid"], name="index_user_firebase_uid"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="index_user_username"),
        ),
        migrations.AddField(
            model_name="splitbill",
            name="user_fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hosted_split_bills",
                to="app.user",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="split_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="app.splitbill",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="app.user",
            ),
        ),
        migrations.AddIndex(
            model_name="splitbill",
            index=models.Index(fields=["name"], name="index_split_bill_name"),
        ),
    ]
