# Generated by Django 3.2.8 on 2022-03-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_bill_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="splitbill",
            old_name="wirhdrawal_number",
            new_name="withdrawal_number",
        ),
    ]
