# Generated by Django 3.2.8 on 2022-04-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_wirhdrawal_number_splitbill_withdrawal_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="amount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="splitbill",
            name="amount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
