# Generated by Django 3.2.8 on 2022-04-15 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_auto_20220415_1008"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("method", models.CharField(max_length=64)),
                ("reference_no", models.CharField(max_length=128)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="app.bill",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
