# Generated by Django 3.2.8 on 2022-04-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference_no",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
