# Generated by Django 3.2.8 on 2022-04-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20220422_0640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="bill",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="app.bill",
            ),
        ),
    ]
