# Generated by Django 3.2.8 on 2022-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_payment_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="bill",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="app.bill",
            ),
        ),
    ]
