# Generated by Django 3.2.8 on 2022-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_auto_20220424_2242"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_bill_id_if_not_deleted",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("bill_id__isnull", False), ("deleted__isnull", True)
                ),
                fields=("bill_id",),
                name="unique_bill_id_if_not_deleted",
            ),
        ),
    ]
