# Generated by Django 3.2.8 on 2022-05-09 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_auto_20220424_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="splitbill",
            name="payout_reference_no",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="splitbill",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="splitbill",
            name="withdrawal_method",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="splitbill",
            name="withdrawal_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
