# Generated by Django 3.2.8 on 2022-05-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_auto_20220509_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                blank=True, default="a@a.com", max_length=50, null=True
            ),
        ),
    ]
